// generate.ts
// Assembles the full app-level DESIGN.md from parsed Figma data.
// Sections 2 and 3 are auto-filled. Sections 4 and 5 are scaffolded with [TODO].

import type { ParsedTokens } from './parse-variables.js'
import type { ParsedComponent } from './parse-components.js'
import { renderTokenSection } from './parse-variables.js'
import { renderComponentSection } from './parse-components.js'
import type { LintReport } from './lint.js'
import { formatLintReport } from './lint.js'

export interface GenerateOptions {
  appName: string
  figmaFileUrl: string
  maintainer: string
  platform: 'ios' | 'android' | 'both'
  includeLintReport: boolean
}

// ─── Static sections ───────────────────────────────────────────────────────

function renderHeader(options: GenerateOptions): string {
  const date = new Date().toISOString().split('T')[0]
  const platformLabel = options.platform === 'ios'
    ? 'iOS (SwiftUI)'
    : options.platform === 'android'
      ? 'Android (Jetpack Compose)'
      : 'iOS (SwiftUI) / Android (Jetpack Compose)'

  return `# DESIGN.md — ${options.appName}
> App-level design system file. Extends /DESIGN.md (root).
> Read root DESIGN.md first, then this file.
> Auto-generated by figma-to-design-md on ${date}. Sections 4 and 5 require manual completion.

---

## 1. App context

\`\`\`
App name        : ${options.appName}
What it does    : [TODO — one functional sentence]
Platform        : ${platformLabel}
Figma file      : ${options.figmaFileUrl}
Token file      : DesignTokens.swift / DesignTokens.kt
Agent tools     : Claude Code, Cursor
Last updated    : ${date}
Maintainer      : ${options.maintainer}
\`\`\`

**Overrides from root DESIGN.md:**
\`\`\`
[TODO — list any root rules this app overrides, and why. If none: "None — all root rules apply."]
\`\`\`

---
`
}

function renderPatternsSection(): string {
  return `
## 4. Composition patterns

> [TODO — fill after completing Phase 4 of the Designer Checklist]
> Copy these from your Figma relationship index documentation.

\`\`\`
Pattern: [PATTERN NAME]
Components : [List in order]
Tokens     : [Key token decisions]
Rules      : [Guardrails specific to this pattern]
When       : [The exact scenario that triggers this pattern]
\`\`\`

<!-- Example to replace:
Pattern: Confirmation dialog (destructive)
Components : Dialog + Alert/warning + Button/destructive + Button/secondary
Tokens     : color/bg/danger on Button/destructive
Rules
  - destructive action on the right (iOS) / bottom (Android)
  - cancel must always be present
When       : deleting data, disconnecting accounts, irreversible actions
-->

---
`
}

function renderGuardrailsSection(): string {
  return `
## 5. App-specific guardrails

> [TODO — fill after completing Phase 4 of the Designer Checklist]
> Copy the ALWAYS/NEVER rules from your Figma guardrails documentation.
> These extend the root DESIGN.md guardrails — do not repeat root rules here.

\`\`\`
ALWAYS
  - [TODO]

NEVER
  - [TODO]
\`\`\`

---
`
}

function renderFooter(options: GenerateOptions): string {
  return `
## 6. What this file does NOT cover

\`\`\`
- Global platform rules → see /DESIGN.md (root)
- Brand voice, tone of voice → see COPY.md if it exists
- Animation / motion → see MOTION.md if it exists
- API / backend contracts → see API docs
- A/B test variants → see product specs
\`\`\`

---

*Owner: ${options.maintainer} — update when app tokens, components, or patterns change.*
*Do not fully auto-generate this file — sections 4 and 5 are human-curated.*
*Re-run \`figma-to-design-md\` to refresh sections 2 and 3 from Figma.*
`
}

// ─── Main generator ────────────────────────────────────────────────────────

export function generateDesignMd(
  tokens: ParsedTokens,
  components: Record<string, ParsedComponent[]>,
  lintReport: LintReport,
  options: GenerateOptions
): string {
  const parts: string[] = []

  parts.push(renderHeader(options))
  parts.push(renderTokenSection(tokens))
  parts.push('---\n')
  parts.push(renderComponentSection(components))
  parts.push('---\n')
  parts.push(renderPatternsSection())
  parts.push(renderGuardrailsSection())
  parts.push(renderFooter(options))

  if (options.includeLintReport) {
    parts.push('\n---\n')
    parts.push('# Appendix: Lint report\n')
    parts.push('> Issues found in your Figma file. Fix these to improve auto-generation quality.\n\n')
    parts.push(formatLintReport(lintReport))
  }

  return parts.join('\n')
}

export function generateLintMd(lintReport: LintReport, appName: string): string {
  const date = new Date().toISOString().split('T')[0]
  return `# Lint report — ${appName}
> Generated by figma-to-design-md on ${date}
> Fix BLOCKING issues first — they prevent the DESIGN.md from being useful to agents.

${formatLintReport(lintReport)}
`
}
